# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    connection-timeout: 5000
    context-path: /

spring:
    # 环境 dev|test|pro
    profiles:
        active:
          dev
        include:
          config
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/,file:${fileupload.filepath},file:${ueditor.localSavePathPrefix}
        chain:
          html-application-cache: false
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
     #spring-activiti
#    activiti:
#        database-schema-update: false
#        #校验流程文件，默认校验resources下的processes文件夹里的流程文件
#        check-process-definitions: false
#        asyncExecutorActivate: false
#        #asyncExecutorEnabled属性设置设置true后将代替那些老的Job executor
#        async-executor-enabled: false
#        job-executor-activate: true
#        process-definition-location-prefix: classpath:/processes/
##       process-definition-location-suffixes:
##       - **.bpmn
##       - **.bpmn20.xml
#        history-level: full
    devtools:
      restart:
        exclude: views/**
# Mybatis配置
mybatis:
    mapperLocations: classpath*:mapper/*/*.xml
    configuration:
        map-underscore-to-camel-case: true

renren:
    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
        # token有效时长，7天，单位秒
        expire: 604800
        header: token
wechat:
  miniapp:
    appid: wx242894521962eefa
    secret: 11efafe3f48cc5da857d4cd016cb2d83

#workflow:
#    workflowPrefix : /processes/

unionpay:
    appid: up_1j74f3i3oeaf_cs00
    appsecret: 6b34321316243e183d1eab6fb3930ba9
    signature: 123456
    tokenurl: https://openapi.unionpay.com/upapi/cardbin/token?app_id=APP_ID&app_secret=APP_SECRET
    cardurl: https://openapi.unionpay.com/upapi/cardbin/cardinfo?token=TOKEN&sign=SIGN&ts=TS
    cardlogo: https://apimg.alipay.com/combo.png?d=cashier&t=bank
    validateAndCacheCardUrl: https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?_input_charset=utf-8&cardNo=CARDNO&cardBinCheck=true